Feature: TriArch Control Room Contacts (slice)
  Generated by scripts/oas-to-gherkin.mjs — do not hand-edit as source of truth.
  Change specs/control-room/contacts.openapi.json and re-run: npm run oas:gherkin

  @contact @api @control-room @smoke
  Scenario: Create Control Room contact leading to 200
    Given the API base URL is configured
    And a valid Authorization bearer token is configured
    And request body is the OpenAPI example for this operation
    When request operation is "POST"
    And request path is "/api/control-room/contacts"
    And the request is sent
    Then response status is 200
    And response JSON has non-empty field "id"
    And response JSON field "firstName" equals the prepared request field "firstName"
    And response JSON field "email" equals the prepared request field "email"
    # Spec example used as base payload: {"firstName":"Qateam","lastName":"ContactDemo","email":"qa.contact.create@example.com","phone":"5551234567","company":"TriArch QAteam"}

  @contact @api @control-room
  Scenario: Create Control Room contact missing email leading to 400
    Given the API base URL is configured
    And a valid Authorization bearer token is configured
    And request body is the OpenAPI example without field "email"
    When request operation is "POST"
    And request path is "/api/control-room/contacts"
    And the request is sent
    Then response status is 400

  @contact @api @control-room
  Scenario: Create Control Room contact without token leading to 401 or 403
    Given the API base URL is configured
    And no Authorization bearer token
    And request body is the OpenAPI example for this operation
    When request operation is "POST"
    And request path is "/api/control-room/contacts"
    And the request is sent
    Then response status is 401 or 403 or 404
